# 1. Original Gensim Word2Vec

## 1.1 SG

In [1]:
# import logging
# logger = logging.getLogger()
# logger.setLevel(logging.DEBUG)
# logging.debug('test')

In [2]:
from evals import get_similarity_score
from datetime import datetime

from fieldembed.models.word2vec import Word2Vec, LineSentence

Little_Wiki_Path = 'corpus/wiki/wiki.txt'
Total_Wiki_Path = 'corpus/WikiTotal/WikiTotal7k_v2.txt'

data_input = LineSentence(Little_Wiki_Path)
data_input = LineSentence(Total_Wiki_Path)


In [4]:
s = datetime.now(); print('+++++Start++++++', s)
# end = datetime.now(); print('+++++End++++++', end, 'Using:',e - s ); 
sg_model = Word2Vec(data_input, size = 200, alpha = 0.025,  min_count = 10, sg = 1, iter=1, workers = 8)
e = datetime.now(); print('+++++End++++++', e, 'Using:',e - s ); 

+++++Start++++++ 2019-05-11 11:31:45.290744
======== Build_vocab based on LineSentence....
o--> Get Vocab Frequency from Scanning Vocab
	Start:  2019-05-11 11:31:45.291899
	End  :  2019-05-11 11:32:56.840986
	Total Time: 0:01:11.549087
o--> Prepare WV's index2word, vocab...
	Start:  2019-05-11 11:32:56.841337
	End  :  2019-05-11 11:32:59.159299
	Total Time: 0:00:02.317962
o--> Compute Token's sampel_int...
	Start:  2019-05-11 11:32:59.159837
	End  :  2019-05-11 11:33:00.215464
	Total Time: 0:00:01.055627
o--> Compute Cum Table
	Start:  2019-05-11 11:33:00.767285
	End  :  2019-05-11 11:33:01.587729
	Total Time: 0:00:00.820444
-------> Prepare Trainable Weight....
o--> Prepare Trainable Parameters
	Start:  2019-05-11 11:33:01.593552
	End  :  2019-05-11 11:33:05.427904
	Total Time: 0:00:03.834352
======== The Voc and Parameters are Ready!
======== Total Time:  0:01:20.136198


======== Training Start ....
======== Training End ......
======== Total Time:  0:08:33.444202
+++++End++++++ 201

In [5]:
# L = []
# for i in data_input:
#     L.append(i) 
# sentences = L[10]

# work1, work2 = sg_model._get_thread_working_mem()
# from fieldembed.models.word2vec_inner import train_batch_sg
# train_batch_sg(sg_model, sentences,  alpha = 0.05, _work = work1, compute_loss = False)

In [6]:
sim_file = 'sources/240.txt'
get_similarity_score(sim_file, token_embedding = sg_model.wv)

sim_file = 'sources/297.txt'
get_similarity_score(sim_file, token_embedding = sg_model.wv)

228 / 240  word pairs appeared in the training dictionary
sources/240.txt : SpearmanrResult(correlation=0.5010249379338645, pvalue=6.81991085481455e-16)
279 / 297  word pairs appeared in the training dictionary
sources/297.txt : SpearmanrResult(correlation=0.585674866818933, pvalue=4.376683806322611e-27)


## 1.2 CBOW

In [7]:
s = datetime.now(); print('+++++Start++++++', s)
# end = datetime.now(); print('+++++End++++++', end, 'Using:',e - s ); 
cb_model = Word2Vec(data_input, size = 200, alpha = 0.025,  min_count = 10, sg = 0, iter=1, workers = 8, cbow_mean=1)
e = datetime.now(); print('+++++End++++++', e, 'Using:',e - s )

+++++Start++++++ 2019-05-11 11:52:03.969928
======== Build_vocab based on LineSentence....
o--> Get Vocab Frequency from Scanning Vocab
	Start:  2019-05-11 11:52:03.970423
	End  :  2019-05-11 11:53:12.919643
	Total Time: 0:01:08.949220
o--> Prepare WV's index2word, vocab...
	Start:  2019-05-11 11:53:12.919776
	End  :  2019-05-11 11:53:14.899298
	Total Time: 0:00:01.979522
o--> Compute Token's sampel_int...
	Start:  2019-05-11 11:53:14.899719
	End  :  2019-05-11 11:53:15.816528
	Total Time: 0:00:00.916809
o--> Compute Cum Table
	Start:  2019-05-11 11:53:16.349709
	End  :  2019-05-11 11:53:17.154975
	Total Time: 0:00:00.805266
-------> Prepare Trainable Weight....
o--> Prepare Trainable Parameters
	Start:  2019-05-11 11:53:17.160645
	End  :  2019-05-11 11:53:20.895644
	Total Time: 0:00:03.734999
======== The Voc and Parameters are Ready!
======== Total Time:  0:01:16.925414


======== Training Start ....
======== Training End ......
======== Total Time:  0:03:47.389295
+++++End++++++ 201

In [8]:
sim_file = 'sources/240.txt'
get_similarity_score(sim_file, token_embedding = cb_model.wv)
sim_file = 'sources/297.txt'
get_similarity_score(sim_file, token_embedding = cb_model.wv)

228 / 240  word pairs appeared in the training dictionary
sources/240.txt : SpearmanrResult(correlation=0.4925495250226306, pvalue=2.452623470576509e-15)
279 / 297  word pairs appeared in the training dictionary
sources/297.txt : SpearmanrResult(correlation=0.6010947501055018, pvalue=8.528554616480385e-29)


## 1.3 Word Similarity

In [9]:
sg_model.wv.most_similar('大学')

[('经济系', 0.825532078742981),
 ('医学院', 0.8067549467086792),
 ('经济学系', 0.8058873414993286),
 ('法学院', 0.8000757098197937),
 ('法律系', 0.7977119088172913),
 ('化学系', 0.7963069677352905),
 ('理工学院', 0.7959226369857788),
 ('理工大学', 0.7888524532318115),
 ('分校', 0.7874594926834106),
 ('理学院', 0.7873160243034363)]

In [10]:
cb_model.wv.most_similar('大学')

[('法学院', 0.7406864762306213),
 ('学院', 0.7253862619400024),
 ('理工学院', 0.7038729190826416),
 ('理工', 0.6829884052276611),
 ('理工大学', 0.6804722547531128),
 ('清华大学', 0.677485466003418),
 ('医学院', 0.6758483648300171),
 ('商学院', 0.6718248724937439),
 ('神学院', 0.658875048160553),
 ('师范大学', 0.6453396677970886)]

# 2. Field Embedding With NLPText

## 2.1 SG

In [11]:
# import logging
# logger = logging.getLogger()
# logger.setLevel(logging.DEBUG)
# logging.debug('test')

In [12]:


from pprint import pprint
from nlptext.base import BasicObject
from datetime import datetime


# s = datetime.now(); print(s)
# ########### Wiki ###########
# CORPUSPath = 'corpus/WikiTotal/'
# # CORPUSPath = 'corpus/wiki/'
# corpusFileIden = '.txt'
# textType   = 'line'
# Text2SentMethod  = 're'
# Sent2TokenMethod = 'sep- '
# TOKENLevel = 'word'
# anno = False
# annoKW = {}
# MaxTokenUnique = 447170
# MaxTextIdx = False
# BasicObject.INIT(CORPUSPath, corpusFileIden, textType, 
#                  Text2SentMethod, Sent2TokenMethod, TOKENLevel, 
#                  anno, annoKW, MaxTextIdx, MaxTokenUnique = MaxTokenUnique)
# e = datetime.now(); print(e)
# print(e -s )


BOB = 'data/WikiTotal/word/Token447174/Pyramid/'
LGU = 'data/WikiTotal/word/Token447174/GrainUnique/'

BasicObject.INIT_FROM_PICKLE(BOB, LGU)

CORPUS	read from pickle file : data/WikiTotal/word/Token447174/Pyramid/CORPUS.p
CORPUS	the length of it is   : 1
FOLDER	read from pickle file : data/WikiTotal/word/Token447174/Pyramid/FOLDER.p
FOLDER	the length of it is   : 1
TEXT	read from pickle file : data/WikiTotal/word/Token447174/Pyramid/TEXT.p
TEXT	the length of it is   : 4717592
SENT	read from pickle file : data/WikiTotal/word/Token447174/Pyramid/SENT.p
SENT	the length of it is   : 11199643
TOKEN	read from pickle file : data/WikiTotal/word/Token447174/Pyramid/TOKEN.p
TOKEN	the length of it is   : 257789077
**************************************** 

token	read from pickle file : data/WikiTotal/word/Token447174/GrainUnique/token.p
token	the length of it is   : 447174
**************************************** 



In [13]:
from fieldembed.models.word2vec import Word2Vec, LineSentence
from datetime import datetime

batch_words = 10000

s = datetime.now(); print('+++++Start++++++', s)
# end = datetime.now(); print('+++++End++++++', end, 'Using:',e - s ); 
sg_model = Word2Vec(nlptext = BasicObject, size = 200, alpha = 0.025, sg = 1, iter=1, workers = 8,batch_words = batch_words)
e = datetime.now(); print('+++++End++++++', e, 'Using:',e - s )

+++++Start++++++ 2019-05-11 12:16:00.639134
======== Build_vocab based on NLPText....
-------> Prepare Vocab....
o--> Get Vocab Frequency from NLPText
o--> Prepare WV's index2word, vocab...
	Start:  2019-05-11 12:16:00.643450
	End  :  2019-05-11 12:16:01.500847
	Total Time: 0:00:00.857397
o--> Compute Token's sampel_int...
	Start:  2019-05-11 12:16:01.501264
	End  :  2019-05-11 12:16:02.420595
	Total Time: 0:00:00.919331
o--> Compute Cum Table
	Start:  2019-05-11 12:16:02.421027
	End  :  2019-05-11 12:16:03.093127
	Total Time: 0:00:00.672100
-------> Prepare Trainable Weight....
o--> Prepare Trainable Parameters
	Start:  2019-05-11 12:16:03.093303
	End  :  2019-05-11 12:16:06.778221
	Total Time: 0:00:03.684918
======== The Voc and Parameters are Ready!
======== Total Time:  0:00:06.138762


======== Training Start ....
Start getting batch infos
2019-05-11 12:16:06.778844
Read info from: data/WikiTotal/word/Token447174/Pyramid/10000_Info.p
2019-05-11 12:16:06.784792
The time of finding 

In [14]:
# sg_model.wv.vectors
sim_file = 'sources/240.txt'
get_similarity_score(sim_file, token_embedding = sg_model.wv)

sim_file = 'sources/297.txt'
get_similarity_score(sim_file, token_embedding = sg_model.wv)

228 / 240  word pairs appeared in the training dictionary
sources/240.txt : SpearmanrResult(correlation=0.48415967120476044, pvalue=8.412810132777828e-15)
279 / 297  word pairs appeared in the training dictionary
sources/297.txt : SpearmanrResult(correlation=0.5877162822168592, pvalue=2.6300047633567268e-27)


## 2.2 CBOW

In [16]:
batch_words = 10000

s = datetime.now(); print('+++++Start++++++', s)
# end = datetime.now(); print('+++++End++++++', end, 'Using:',e - s ); 
cbow_model = Word2Vec(nlptext = BasicObject, size = 200, alpha = 0.025, sg = 0, iter=1, workers = 8,batch_words = batch_words)
e = datetime.now(); print('+++++End++++++', e, 'Using:',e - s )

+++++Start++++++ 2019-05-11 15:06:39.581727
======== Build_vocab based on NLPText....
-------> Prepare Vocab....
o--> Get Vocab Frequency from NLPText
o--> Prepare WV's index2word, vocab...
	Start:  2019-05-11 15:06:39.588578
	End  :  2019-05-11 15:06:40.314871
	Total Time: 0:00:00.726293
o--> Compute Token's sampel_int...
	Start:  2019-05-11 15:06:40.315332
	End  :  2019-05-11 15:06:41.246531
	Total Time: 0:00:00.931199
o--> Compute Cum Table
	Start:  2019-05-11 15:06:41.246837
	End  :  2019-05-11 15:06:41.861601
	Total Time: 0:00:00.614764
-------> Prepare Trainable Weight....
o--> Prepare Trainable Parameters
	Start:  2019-05-11 15:06:41.862079
	End  :  2019-05-11 15:06:45.698546
	Total Time: 0:00:03.836467
======== The Voc and Parameters are Ready!
======== Total Time:  0:00:06.117057


======== Training Start ....
Start getting batch infos
2019-05-11 15:06:45.699387
Read info from: data/WikiTotal/word/Token447174/Pyramid/10000_Info.p
2019-05-11 15:06:45.705375
The time of finding 

In [17]:
# sg_model.wv.vectors
sim_file = 'sources/240.txt'
get_similarity_score(sim_file, token_embedding = cbow_model.wv)

sim_file = 'sources/297.txt'
get_similarity_score(sim_file, token_embedding = cbow_model.wv)

228 / 240  word pairs appeared in the training dictionary
sources/240.txt : SpearmanrResult(correlation=0.4477823747873547, pvalue=1.2133279327426804e-12)
279 / 297  word pairs appeared in the training dictionary
sources/297.txt : SpearmanrResult(correlation=0.5713257961095262, pvalue=1.421612667715381e-25)


## 2.3 Word Similarity

In [18]:
sg_model.wv.most_similar('大学')

[('经济系', 0.8247467279434204),
 ('法学院', 0.8213362693786621),
 ('化学系', 0.8110883831977844),
 ('法律系', 0.8061723113059998),
 ('理工学院', 0.7952156066894531),
 ('社会学系', 0.790824294090271),
 ('历史系', 0.7888401746749878),
 ('文学院', 0.788623571395874),
 ('理工大学', 0.7878395318984985),
 ('分校', 0.7821967601776123)]

In [19]:
cbow_model.wv.most_similar('大学')

[('理工学院', 0.7526243925094604),
 ('法学院', 0.7520142197608948),
 ('学院', 0.7396164536476135),
 ('理工大学', 0.7357087135314941),
 ('理工', 0.7103638052940369),
 ('商学院', 0.7071322202682495),
 ('医学院', 0.6969972848892212),
 ('清华大学', 0.6865324378013611),
 ('神学院', 0.6818000078201294),
 ('师范大学', 0.6764853000640869)]

## 2.4 Coding

### 2.4.1 Play with NLPText

In [20]:


from pprint import pprint
from nlptext.base import BasicObject
from datetime import datetime


s = datetime.now(); print(s)
########### Wiki ###########
# CORPUSPath = 'corpus/WikiTotal/'
CORPUSPath = 'corpus/wiki/'
corpusFileIden = '.txt'
textType   = 'line'
Text2SentMethod  = 're'
Sent2TokenMethod = 'sep- '
TOKENLevel = 'word'
anno = False
annoKW = {}
MaxTokenUnique = 447170
MaxTextIdx = False

BasicObject.INIT(CORPUSPath, corpusFileIden, textType, 
                 Text2SentMethod, Sent2TokenMethod, TOKENLevel, 
                 anno, annoKW, MaxTextIdx, MaxTokenUnique = MaxTokenUnique)
e = datetime.now(); print(e)
print(e -s )

# BOB = 'data/WikiTotal/word/Token447174/Pyramid/'
# LGU = 'data/WikiTotal/word/Token447174/GrainUnique/'

# BasicObject.INIT_FROM_PICKLE(BOB, LGU)

2019-05-11 15:09:41.980963
'File'
corpus/wiki/wiki.txt
Total Num of All    Tokens 31271
The Total Number of Tokens: 31271
Counting the number unique Tokens...          	 2019-05-11 15:09:42.044480
		Done!
Generating Dictionary of Token Unique...	 2019-05-11 15:09:42.049339
		The length of DTU is: 6905 	 2019-05-11 15:09:42.050844
Generating the ORIGTokenIndex...       	 2019-05-11 15:09:42.050904
		The idx of token is: 0 	 2019-05-11 15:09:42.051139
		Done!
Only Keep First 447170 Tokens.
The coverage rate is: 0.0
Total Num of Unique Tokens 6905
		Write to: data/wiki/word/Token6905/token.tsv
CORPUS	it is Dumped into file: data/wiki/word/Token6905/Pyramid/CORPUS.p
CORPUS	the length of it is   : 1
FOLDER	it is Dumped into file: data/wiki/word/Token6905/Pyramid/FOLDER.p
FOLDER	the length of it is   : 1
TEXT	it is Dumped into file: data/wiki/word/Token6905/Pyramid/TEXT.p
TEXT	the length of it is   : 533
SENT	it is Dumped into file: data/wiki/word/Token6905/Pyramid/SENT.p
SENT	the length of 

In [21]:
import numpy as np
sentences_endidx = BasicObject.SENT['EndIDXTokens']
sentences_endidx[:10]

array([  99,  247,  278,  312,  637,  726,  821,  902,  980, 1023],
      dtype=uint32)

In [22]:
tokens_vocidx = BasicObject.TOKEN['ORIGTokenIndex']
# the first sentence
tokens_vocidx[0:99]

array([  52,  402,  657,  658,   27,    6,  131,  117,   66,  402,  659,
          4, 1401, 1088,   24, 2855,    5,   52,  402,  657,  658,   50,
          6,    4, 2856,   73,  439,    4,  752, 2857, 1402, 1403,    6,
       1851, 1089, 2858,  403, 1090,   30, 1852,  117,  522,  147,   13,
        892,  659,    5, 1853, 2859,  117,  182,   34,  753, 1404,   19,
        338,    5,  402,  659,    4, 1401, 1088,   52,  402,  657,  658,
        372,  893, 2860,   77, 1405,    4, 1091,  304, 1854, 1092,  305,
          4,  439, 1093,   31,  754,   16,  137, 1855,  155, 1092,  305,
       1406,    4,   18,  125,  755, 1092,  305,   16, 2861,    4, 2862],
      dtype=uint32)

In [23]:
LTU, DTU = BasicObject.TokenUnique
LTU[:10]

['</pad>', '</start>', '</end>', '</unk>', '的', '在', '年', '月', '是', '和']

### 2.4.2 Generate `indexes` and `sentence_idx`

In [24]:
total_words = len(tokens_vocidx)           
total_examples  = len(sentences_endidx)

In [25]:
batch_words = 10000

total_words = total_words or len(tokens_vocidx)           
total_examples  = total_examples or len(sentences_endidx)

batch_end_st_idx_list = []
job_no = 0 # job_num
while True:
    job_no = job_no + 1
    batch_token_progress = job_no * batch_words  # 

    if batch_token_progress >= total_words:
        
        # if touch the bottom, go to the end and terminate the loop
        batch_end_st_idx_list.append(total_examples)
        # # This won't work: print('Current batch token number:', sentences_endidx[total_examples]) 
        print("Last sentence's end tk loc:", sentences_endidx[total_examples-1])
        break

    # if not, find the correct end sentence loc_id for this batch
    batch_end_st_idx = np.argmax(sentences_endidx > batch_token_progress)
    batch_end_st_idx_list.append(batch_end_st_idx)
    
    print('Current batch token number:', sentences_endidx[batch_end_st_idx])
    print("Last sentence's end tk loc:", sentences_endidx[batch_end_st_idx-1])

    
print(batch_end_st_idx_list, '\n')

for idx in range(job_no):

    # start and end are batch's start sentence loc_id and end sentence loc_id
    # as python routines, batch is [start, end), left close right open
    start = batch_end_st_idx_list[idx-1] if idx > 0 else 0
    end   = batch_end_st_idx_list[idx]

    # print(start, end)
    # find the start sentence's start token loc_id, and
    # find the end sentence's start token loc_id. (as the end sentence is exluded)
    token_start = sentences_endidx[start-1] if start > 0 else 0
    token_end   = sentences_endidx[end  -1]

    indexes     = tokens_vocidx[token_start:token_end] # dtype = np.uint32
    sentence_idx = np.array([i-token_start for i in sentences_endidx[start: end]], dtype = np.uint32)
    print('The start and end sent loc_id:', start, end)
    print('The token start and end loc idx in each batch:', token_start, token_end)
    print(sentence_idx[-1], len(indexes), '\n')
    
print(end == len(sentences_endidx))
print(token_end == len(tokens_vocidx))


Current batch token number: 10073
Last sentence's end tk loc: 9993
Current batch token number: 20007
Last sentence's end tk loc: 19978
Current batch token number: 30031
Last sentence's end tk loc: 29911
Last sentence's end tk loc: 31271
[165, 346, 515, 533] 

The start and end sent loc_id: 0 165
The token start and end loc idx in each batch: 0 9993
9993 9993 

The start and end sent loc_id: 165 346
The token start and end loc idx in each batch: 9993 19978
9985 9985 

The start and end sent loc_id: 346 515
The token start and end loc idx in each batch: 19978 29911
9933 9933 

The start and end sent loc_id: 515 533
The token start and end loc idx in each batch: 29911 31271
1360 1360 

True
True


### 2.4.3 Test Cython Function with  `indexes` and `sentence_idx`


`indexes` and `sentences_idx`

In [26]:
print(len(indexes))
indexes

1360


array([ 700, 6716,  125, ...,   64,   22,  111], dtype=uint32)

In [27]:
print(len(sentence_idx))
sentence_idx#[:10]

18


array([ 120,  190,  244,  266,  395,  537,  566,  686,  727,  859,  893,
        952, 1008, 1032, 1194, 1238, 1352, 1360], dtype=uint32)

In [28]:
sent_idx = 3

start_token = sentence_idx[sent_idx-1] if sent_idx > 0 else 0
end_token = sentence_idx[sent_idx]

print(start_token, end_token)
' '.join([LTU[i] for i in indexes[start_token:end_token]])

244 266


'建国 后林 一直 离群索居 从不 介入 将 帅圈子 他 不 串门 不见客 登门 来 拜访 的 人 多数 也 被 叶群挡 驾'

In [ ]:
from fieldembed.models.word2vec_inner import train_batch_sg_nlptext

from fieldembed.models.word2vec import Word2Vec, LineSentence
from datetime import datetime
Little_Wiki_Path = 'corpus/wiki/wiki.txt'
data_input = LineSentence(Little_Wiki_Path)
# data_input = LineSentence(Total_Wiki_Path)
start = datetime.now()

print(start)
# min_count must be set as 0
sg_model = Word2Vec(data_input, size = 200, alpha = 0.025,  min_count = 0, sg = 1, iter=1, workers = 8)
end = datetime.now()
time = end - start

print(end)
print(time)


work1, work2 = sg_model._get_thread_working_mem()

train_batch_sg_nlptext(sg_model, indexes, sentence_idx, alpha = 0.05, _work = work1, compute_loss = False)

under 10 jobs per worker: consider setting a smaller `batch_words' for smoother alpha decay


2019-05-11 15:09:48.621704
======== Build_vocab based on LineSentence....
o--> Get Vocab Frequency from Scanning Vocab
	Start:  2019-05-11 15:09:48.622155
	End  :  2019-05-11 15:09:48.633144
	Total Time: 0:00:00.010989
o--> Prepare WV's index2word, vocab...
	Start:  2019-05-11 15:09:48.633348
	End  :  2019-05-11 15:09:48.642429
	Total Time: 0:00:00.009081
o--> Compute Token's sampel_int...
	Start:  2019-05-11 15:09:48.642712
	End  :  2019-05-11 15:09:48.663886
	Total Time: 0:00:00.021174
o--> Compute Cum Table
	Start:  2019-05-11 15:09:48.669163
	End  :  2019-05-11 15:09:48.676158
	Total Time: 0:00:00.006995
-------> Prepare Trainable Weight....
o--> Prepare Trainable Parameters
	Start:  2019-05-11 15:09:48.676345
	End  :  2019-05-11 15:09:48.745411
	Total Time: 0:00:00.069066
======== The Voc and Parameters are Ready!
======== Total Time:  0:00:00.123636


======== Training Start ....
======== Training End ......
======== Total Time:  0:00:00.098370
2019-05-11 15:09:48.921949